# Generated by Django 4.1.5 on 2023-01-11 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud_user', '0002_alter_user_addres_alter_user_date_birth_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='addres',
            new_name='address',
        ),
    ]
