# Generated by Django 4.1.5 on 2023-01-12 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_user', '0004_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mobile_phone',
            field=models.IntegerField(null=True),
        ),
    ]
